# Generated by Django 4.1.7 on 2023-05-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pdated',
            new_name='updated',
        ),
    ]
